function displayAsciiTextFile(filename, asciiDisplay, asciiText)
    % Displays ASCII art from a text file in a figure.
    %
    % Inputs:
    %   filename (string) - Path to the ASCII text file (.txt) generated by img2txt.
    %   asciiDisplay (optional) - Handle to an existing UI text component.
    %   asciiMatrix (optional) - Character matrix of the ASCII art.
    
    if nargin < 2
        % If no asciiDisplay or asciiMatrix passed in, create new display setup
        [asciiDisplay, asciiText, ~] = setupAsciiDisplay(filename);
    end

    set(asciiDisplay, 'String', asciiText);
end
